name: LaTeX Book PDF CI/CD
on:
  push:
    branches:
      - main
    paths:
      - 'book.tex'
jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Cache LaTeX packages
      uses: actions/cache@v4
      with:
        path: /usr/share/texlive
        key: texlive-${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          texlive-${{ runner.os }}-

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra fonts-jetbrains-mono
    
    - name: Compile LaTeX
      run: |
        xelatex -interaction=nonstopmode book.tex
        while grep -q "Rerun to get" book.log; do
          xelatex -interaction=nonstopmode book.tex
        done
      continue-on-error: true  

    - name: Upload LaTeX log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: latex-logs
        path: |
          book.log

    - name: Check for compilation errors
      run: |
        if grep -q "Fatal error" book.log; then
          echo "LaTeX compilation failed!"
          exit 1
        fi          

    - name: Commit and Push PDF
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: book.pdf
        commit_message: 'CI: Auto-generated book.pdf from book.tex'
        branch: ${{ github.ref_name }}
        commit_user_name: GitHub Actions Bot
        commit_user_email: actions@github.com
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-book-pdf
        path: book.pdf

    - name: Create pages folder
      run: mkdir -p book && cp book.pdf book/

    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'book'